// src/sitemapRoutes.js
const routes = [
  "/", 
  "/order",
  "/about",
  "/terms-and-condition",
  "/privacy-policy",
  "/contact",
  "/warranty",
  "/request-a-parts",

  // Dynamic used-auto-parts pages
  "/used-auto-parts/acura",
  "/used-auto-parts/bmw",
  "/used-auto-parts/buick",
  "/used-auto-parts/cadillac",
  "/used-auto-parts/chevy",
  "/used-auto-parts/chrysler",
  "/used-auto-parts/daewoo",
  "/used-auto-parts/daihatsu",
  "/used-auto-parts/dodge",
  "/used-auto-parts/eagle",
  "/used-auto-parts/ford",
  "/used-auto-parts/gmc",
  "/used-auto-parts/honda",
  "/used-auto-parts/hyundai",
  "/used-auto-parts/isuzu",
  "/used-auto-parts/jaguar",
  "/used-auto-parts/jeep",
  "/used-auto-parts/kia",
  "/used-auto-parts/landrover",
  "/used-auto-parts/lexus",
  "/used-auto-parts/lincoln",
  "/used-auto-parts/mazda",
  "/used-auto-parts/mercedes",
  "/used-auto-parts/mercury",
  "/used-auto-parts/mini-cooper",
  "/used-auto-parts/mitsubishi",
  "/used-auto-parts/nissan",
  "/used-auto-parts/oldsmobile",
  "/used-auto-parts/plymouth",
  "/used-auto-parts/pontiac",
  "/used-auto-parts/porsche",
  "/used-auto-parts/saab",
  "/used-auto-parts/saturn",
  "/used-auto-parts/scion",
  "/used-auto-parts/subaruu",
  "/used-auto-parts/suzuki",
  "/used-auto-parts/toyota",
  "/used-auto-parts/volkswagen",
  "/used-auto-parts/volvo",
];

export default routes;